Vagrant.configure("2") do |config|
                               
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.0.2.1"
  config.vm.network "forwarded_port", guest: 9000, host: 9000
    
  config.vm.synced_folder "./../../shared", "/shared"
  
  config.vm.define "h-primary" 

  config.vm.provider "virtualbox" do |vb|
    vb.name = "h-primary" 
    vb.memory = "4096"         
  end

  config.vm.provision "shell" do |s|
    s.binary = true
    s.inline = "sudo chmod -R +x /vagrant"
    s.inline = "sudo chmod -R +x /shared"
    s.inline = "sudo /vagrant/scripts/install.sh"
  end 

end
